/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: d481fdb69a8c449753375d30efacb3d2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "LiveRoomDurableObject";
	}
	interface Env {
		CACHE: KVNamespace;
		BLOB_STORAGE: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		LIVE_ROOM_DO: DurableObjectNamespace<import("./src/worker").LiveRoomDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
